name: Deploy Project
on: push
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
          check-latest: true
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: go get .
      - name: Run tests
        run: go test -v
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
          check-latest: true
      - name: Install dependencies
        run: go get .
      - name: Build project
        run: go build -o main .
      - name: Deploy project
        run: echo "Deploying..."


